In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [150]:
df = pd.read_csv('../data/raw_osteoporosis_data.csv')

In [152]:

df.head()

,Id,Age,Gender,Hormonal Changes,Family History,Race/Ethnicity,Body Weight,Calcium Intake,Vitamin D Intake,Physical Activity,Smoking,Alcohol Consumption,Medical Conditions,Medications,Prior Fractures,Osteoporosis
0,104866,69,Female,Normal,Yes,Asian,Underweight,Low,Sufficient,Sedentary,Yes,Moderate,Rheumatoid Arthritis,Corticosteroids,Yes,1
1,101999,32,Female,Normal,Yes,Asian,Underweight,Low,Sufficient,Sedentary,No,NaN,NaN,NaN,Yes,1
2,106567,89,Female,Postmenopausal,No,Caucasian,Normal,Adequate,Sufficient,Active,No,Moderate,Hyperthyroidism,Corticosteroids,No,1
3,102316,78,Female,Normal,No,Caucasian,Underweight,Adequate,Insufficient,Sedentary,Yes,NaN,Rheumatoid Arthritis,Corticosteroids,No,1
4,101944,38,Male,Postmenopausal,Yes,African American,Normal,Low,Sufficient,Active,Yes,NaN,Rheumatoid Arthritis,NaN,Yes,1

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1958 entries, 0 to 1957
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   1958 non-null   int64
 1   Age                  1958 non-null   int64
 2   Gender               1958 non-null   object
 3   Hormonal Changes     1958 non-null   object
 4   Family History       1958 non-null   object
 5   Race/Ethnicity       1958 non-null   object
 6   Body Weight          1958 non-null   object
 7   Calcium Intake       1958 non-null   object
 8   Vitamin D Intake     1958 non-null   object
 9   Physical Activity    1958 non-null   object
 10  Smoking              1958 non-null   object
 11  Alcohol Consumption  970 non-null    object
 12  Medical Conditions   1311 non-null   object
 13  Medications          973 non-null    object
 14  Prior Fractures      1958 non-null   object
 15  Osteoporosis         1958 non-null   int64
dtypes: int64(3), object(13)
memory usage: 244.9+ KB

In [156]:
df.rename(columns={'Id': 'id', 'Age': 'age', 'Gender': 'gender', 'Hormonal Changes': 'hormonal_changes', 'Family History': 'family_history', 'Race/Ethnicity': 'race_Ethnicity', 'Body Weight': 'body_Weight', 'Calcium Intake': 'calcium_Intake', 'Vitamin D Intake': 'vitamin_D_Intake', 'Physical Activity': 'physical_Activity', 'Smoking': 'smoking', 'Alcohol Consumption': 'alcohol_Consumption', 'Medical Conditions': 'medical_Conditions', 'Medications': 'medications', 'Prior Fractures': 'prior_Fractures', 'Osteoporosis': 'osteoporosis'}, inplace=True)

In [158]:
df.head()

,id,age,gender,hormonal_changes,family_history,race_Ethnicity,body_Weight,calcium_Intake,vitamin_D_Intake,physical_Activity,smoking,alcohol_Consumption,medical_Conditions,medications,prior_Fractures,osteoporosis
0,104866,69,Female,Normal,Yes,Asian,Underweight,Low,Sufficient,Sedentary,Yes,Moderate,Rheumatoid Arthritis,Corticosteroids,Yes,1
1,101999,32,Female,Normal,Yes,Asian,Underweight,Low,Sufficient,Sedentary,No,NaN,NaN,NaN,Yes,1
2,106567,89,Female,Postmenopausal,No,Caucasian,Normal,Adequate,Sufficient,Active,No,Moderate,Hyperthyroidism,Corticosteroids,No,1
3,102316,78,Female,Normal,No,Caucasian,Underweight,Adequate,Insufficient,Sedentary,Yes,NaN,Rheumatoid Arthritis,Corticosteroids,No,1
4,101944,38,Male,Postmenopausal,Yes,African American,Normal,Low,Sufficient,Active,Yes,NaN,Rheumatoid Arthritis,NaN,Yes,1

In [160]:
df.isnull().sum()

id                       0
age                      0
gender                   0
hormonal_changes         0
family_history           0
race_Ethnicity           0
body_Weight              0
calcium_Intake           0
vitamin_D_Intake         0
physical_Activity        0
smoking                  0
alcohol_Consumption    988
medical_Conditions     647
medications            985
prior_Fractures          0
osteoporosis             0
dtype: int64

In [162]:
# df['alcohol_Consumption'].fillna('None', inplace=True)
# df['medical_Conditions'].fillna('None', inplace=True)
# df['medications'].fillna('None', inplace=True)

In [164]:
df['alcohol_Consumption'] = df['alcohol_Consumption'].fillna('None')
df['medical_Conditions'] = df['medical_Conditions'].fillna('None')
df['medications'] = df['medications'].fillna('None')

In [168]:
df.drop(['id'], axis=1, inplace=True)

In [176]:
for column in df.select_dtypes(include='object').columns:
    print(df[column].value_counts())
    print("\n")

gender
Male      992
Female    966
Name: count, dtype: int64


hormonal_changes
Normal            981
Postmenopausal    977
Name: count, dtype: int64


family_history
No     998
Yes    960
Name: count, dtype: int64


race_Ethnicity
African American    681
Caucasian           646
Asian               631
Name: count, dtype: int64


body_Weight
Normal         1027
Underweight     931
Name: count, dtype: int64


calcium_Intake
Low         1004
Adequate     954
Name: count, dtype: int64


vitamin_D_Intake
Sufficient      1011
Insufficient     947
Name: count, dtype: int64


physical_Activity
Active       1021
Sedentary     937
Name: count, dtype: int64


smoking
Yes    982
No     976
Name: count, dtype: int64


alcohol_Consumption
None        988
Moderate    970
Name: count, dtype: int64


medical_Conditions
Hyperthyroidism         678
None                    647
Rheumatoid Arthritis    633
Name: count, dtype: int64


medications
None               985
Corticosteroids    973
Name: count, dtype: int64


prior_Fractures
Yes    983
No     975
Name: count, dtype: int64

In [178]:
df['medical_Conditions'].describe()

count                1958
unique                  3
top       Hyperthyroidism
freq                  678
Name: medical_Conditions, dtype: object